import Vue from 'vue'
import Icon from 'vue-awesome/components/Icon.vue'
import 'vue-awesome/icons'

import 'vue-awesome/icons/keyboard'
import 'vue-awesome/icons/desktop'
import 'vue-awesome/icons/file-code'
import 'vue-awesome/icons/laptop-code'
import 'vue-awesome/icons/filter'
import 'vue-awesome/icons/cubes'
import 'vue-awesome/icons/code-branch'
import 'vue-awesome/icons/fire-alt'
import 'vue-awesome/icons/database'
import 'vue-awesome/icons/camera'
import 'vue-awesome/icons/bezier-curve'
import 'vue-awesome/icons/edit'
import 'vue-awesome/icons/film'
import 'vue-awesome/icons/microphone'
import 'vue-awesome/icons/code'
import 'vue-awesome/icons/people-carry'
import 'vue-awesome/icons/caret-square-down'
import 'vue-awesome/icons/arrow-circle-left'
import 'vue-awesome/icons/arrow-circle-right'
import 'vue-awesome/icons/link'
import 'vue-awesome/icons/window-close'
import 'vue-awesome/icons/book-reader'
import 'vue-awesome/icons/gamepad'
import 'vue-awesome/icons/swatchbook'
import 'vue-awesome/icons/camera-retro'
import 'vue-awesome/icons/search-plus'
import 'vue-awesome/icons/palette'
import 'vue-awesome/icons/blender'
import 'vue-awesome/icons/bars'
import 'vue-awesome/icons/home'
import 'vue-awesome/icons/address-card'
import 'vue-awesome/icons/book-open'
import 'vue-awesome/icons/book'
import 'vue-awesome/icons/microphone'
import 'vue-awesome/icons/dice'
import 'vue-awesome/icons/envelope-open-text'

Vue.component('Icon', Icon)